import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/Hi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required']});
const page=await browser.newPage({viewport:{width:1440,height:900}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto('http://localhost:8090');
await page.waitForTimeout(25000);
await page.screenshot({path:'qa/loading.png'});
await page.getByText('START',{exact:true}).click();
await page.waitForTimeout(9000);
await page.screenshot({path:'qa/idle.png'});
await page.mouse.move(720,470);await page.waitForTimeout(3500);
await page.screenshot({path:'qa/monitor.png'});
console.log(JSON.stringify({errors:errors.slice(0,5)}));
await browser.close();
